= FreeBSD Audio and Jack
Florian Walpen <dev@submerge.ch>
:toc:

These notes are a mixture of guidelines, configuration details and setup
recommendations for using https://jackaudio.org/[Jack Audio Server] on
https://jackaudio.org/[FreeBSD]. Most of it is based on my experiments and
findings while doing a rewrite of the Jack driver backend for FreeBSD. I am
neither a sound engineer nor an expert on FreeBSD system internals though.


== Setup and Use Cases

Requirements vary greatly between different use cases. It makes sense to be
aware of what you want to achieve, before going into the details.

=== Playback Only

This is the simplest use case, given that there is no need to synchronize the
output with external events. Latency settings can be relaxed, longer processing
cycles and large buffers keep CPU load and system timing constraints at a
minimum. If you have to synchronize with external events, see the section
on live processing.


=== Recording

Usually recording also includes playback, to e.g. capture a guitar playing
along a previously recorded drum track. Certainly you want the timing of the
guitar track to match the drums. Still there is no need to go _low latency_,
since audio software can _compensate_ the latency while recording. But it's
essential to have _stable latency_, for multiple takes and also between
recording sessions.

[NOTE]
====

While it's technically possible to use different devices for recording and
playback, this is not recommended. It may cause problems since the devices are
not synchronized and run at a slightly different speed.

====


=== Monitoring

Obviously you want to hear your instrument playing while recording. It is
_highly preferable_ to circumvent the software stack altogether and have an
external monitoring solution in hardware. This could be a complete mixing desk
or just some direct monitoring knobs on your audio interface. Going through the
software stack will introduce _noticeable_ latency.

If you have to do monitoring through Jack, use extra low latency settings.
Maybe it helps to run Jack as a high priority process and setup the monitoring
directly as connections on the Jack server, bypassing other Jack clients
(untested).


=== Live Processing

This means use cases where low latency is crucial, like add some plugin effects
to a live performance, emulating guitar amps or playing a software synthesizer.
To be honest, I don't think FreeBSD is the right tool for this job. There is no
realtime support, no good way to run multiple user processes at high priority,
and most hardware drivers set a lower limit to the duration of processing
cycles.

Don't do this unless your sounds are very timing insensitive. Or prove me wrong.


=== Hardware

There seem to be only two drivers geared towards audio interfaces for music
creation and recording. The other pcm drivers (`man sound`) _do_ work with
Jack. But a soundblaster or internal sound card may have problems recording a
guitar or driving your studio headphones.

snd_hdspe::
RME HDSPe AIO and HDSPe RayDAT, professional PCI cards from RME.
snd_uaudio::
USB audio interfaces, most class compliant devices should be supported.

Unfortunately I never got my hands on one of those expensive RME cards.
Supposedly they would provide the lowest latency and the most channels you can
get with FreeBSD.

USB audio interfaces are more common, affordable, and come in many varieties
suitable for different setups. The `snd_uaudio` driver implements the protocol
for generic USB audio class devices, so look out for a _Class Compliant_
device.

TIP: Class Compliant devices are often marketed as being "iPad compatible".

There are limitations with USB audio devices though:

* Some are not completely Class Compliant, only tested on Windows and Mac.
* Some need USB quirks to get them running.
* High sample rates with lots of channels may not be supported.
* Hardware mixing and routing is typically not accessible in software.

In any case, `snd_uaudio` works with audio blocks of length 2ms or more, which
places a lower boundary on the latency you can achieve -- expect at least 5ms
input and 7ms output latency for Jack.



== Device Settings

If your hardware is recognized correctly, it appears in the system logs as pcm
device

  # dmesg | grep pcm
  pcm0: <ATI R6xx (HDMI)> at nid 3 on hdaa0
  pcm1: <Realtek ALC262 (Analog)> at nid 21 and 24,25,26 on hdaa1
  pcm2: <Realtek ALC262 (Front Analog Headphones)> at nid 27 on hdaa1
  pcm3: <USB audio> on uaudio0

and also by device driver

  # dmesg | grep uaudio
  uaudio0 on uhub2
  uaudio0: <Roland EDIROL UA-25EX, rev 1.10/1.00, addr 2> on usbus4
  uaudio0: Play[0]: 48000 Hz, 2 ch, 24-bit S-LE PCM format, 2x2ms buffer.
  uaudio0: Record[0]: 48000 Hz, 2 ch, 24-bit S-LE PCM format, 2x2ms buffer.
  uaudio0: MIDI sequencer.
  pcm3: <USB audio> on uaudio0
  uaudio0: No HID volume keys found.

Otherwise check the
https://docs.freebsd.org/en/books/handbook/multimedia/[handbook] on how to
setup your sound card.

=== Loader

These settings are available at boot time when loading the drivers. Most of
them are optional though, apply as needed. This example is specific to USB
audio devices (`man snd_uaudio`), not all drivers have something similar.

./boot/loader.conf
----
snd_uaudio_load="YES" # <1>
hw.usb.uaudio.buffer_ms="2" # <2>
hw.usb.uaudio.default_channels="2" # <3>
hw.usb.uaudio.default_bits="32"
hw.usb.uaudio.default_rate="48000"
hw.usb.quirk.0="0x0a4a 0xc150 0x0000 0xffff UQ_CFG_INDEX_1" # <4>
hw.usb.quirk.1="0x0582 0x00e6 0x0000 0xffff UQ_AU_VENDOR_CLASS"
----
<1> Force loading the driver, prerequisite for other settings.
<2> Audio buffer length processed at once by the driver, from 2ms to 8ms.
<3> Default number of channels, sample size and sample rate.
<4> Quirks to make some incompatible devices work.

IMPORTANT: I highly recommend to set the driver buffer length to 2ms for USB
devices. The finer granularity of processing makes Jack cycles more regular and
helps both with stable latency and low latency requirements.

If a USB device supports multiple configurations, the driver will choose the
"best" one. You can make it prefer a different channel count, sample size and
sample rate by setting the defaults here. Quirks are needed when devices don't
adhere to standards and only work with some special treatment. See `man
usb_quirk`.

